# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e98cbdf1fc4c92a44ef4f8f62013893699fbbfd9b718630d1f833ce34747aabc3b9c2638f76047f80225c4a5ba73e70c05dd7762e41e86065348e23e4c07c41b

test:
  secret_key_base: c0cf72bac9d387f1f4461ccfece509e90f020029f109271658ec51114b586b26ce3c63ba751363c8d580ebeefaf71fd9f79cf0757e7bc5e7dcca702c35f045ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
